accordion/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', accordionView)
]

ajax/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ajaxViews),
    path('response/', get_book_request)
]

kegiatan/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', kegiatanView, name='kegiatan')
]

matkul/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', matkulView, name='catat'),
    path('all/<int:id>', matkulAllView, name='all')
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('matkul.urls')),
    path('kegiatan/', include('kegiatan.urls')),
    path('accordion/', include('accordion.urls')),
    path('ajax/', include('ajax.urls')),
    path('wangi/', include('wangi.urls'))
]

wangi/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', loginView, name='loginbase'),
    path('success/', loginSuccessView, name='loginsuccess'),
    path('error/', loginErrorView, name='loginerror'),
    path('signup/', signupView, name='signup'),
    path('logout/', logoutView, name='logout')
]

accordion/models.py
from django.db import models

# Create your models here.

ajax/models.py
from django.db import models

# Create your models here.

kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length = 20)

class Orang(models.Model):
    nama = models.CharField(max_length = 20)
    kegiatan = models.ManyToManyField(Kegiatan)

matkul/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    namaMatkul = models.CharField(max_length=99)
    dosen = models.CharField(max_length = 20)
    sks = models.IntegerField()
    deskripsi = models.CharField(max_length=120)
    semester = models.CharField(max_length=15)
    ruangKelas = models.CharField(max_length=7)

    def __unicode__(self):
        return self.pk

    def __str__(self):
        return self.namaMatkul

wangi/models.py
from django.db import models

# Create your models here.

kegiatan/forms.py
from django import forms
from .models import *

class kegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ('namaKegiatan',)

class orangForm(forms.ModelForm):
    class Meta:
        model = Orang
        fields = ('nama',)

matkul/forms.py
from django import forms
from matkul.models import MataKuliah

class matkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = ('namaMatkul', 'dosen', 'sks', 'deskripsi', 'semester','ruangKelas')
        labels = {
            'namaMatkul' : 'Nama Matkul',
            'sks' : 'SKS',
            'ruangKelas' : 'Ruang Kelas'
        }

class matkulDelete(forms.Form):
    choice = forms.ModelChoiceField(queryset= MataKuliah.objects.all())

accordion/views.py
from django.shortcuts import render

# Create your views here.
def accordionView(request):
    return render(request, 'accordion.html')

ajax/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
def ajaxViews(request):
    return render(request, 'ajax.html')

def get_book_request(request):
    query = request.GET.get('query')
    url = f"https://www.googleapis.com/books/v1/volumes?q={query}"
    response = requests.get(url=url)
    return JsonResponse(data=response.json())

kegiatan/views.py
from django.shortcuts import render
from .forms import *

# Create your views here.
def kegiatanView(request):
    context = {}
    form1 = kegiatanForm()
    form2 = orangForm()
    kegiatan = Kegiatan.objects.all()
    context['form1'] = form1
    context['form2'] = form2
    context['kegiatan'] = kegiatan
    if request.method == 'POST':
        form1 = kegiatanForm(request.POST)
        form2 = orangForm(request.POST)
        if form1.is_valid():
            form1.save()
            context['kegiatanSukses'] = True
        elif form2.is_valid():
            kegiatan2 = Kegiatan.objects.get(id=request.POST.get('pkKegiatan'))
            orang = Orang.objects.create(nama=form2.cleaned_data.get('nama'))
            orang.kegiatan.add(kegiatan2)
    return render(request, 'kegiatan.html', context)

matkul/views.py
from django.shortcuts import render
from .forms import *
from .models import MataKuliah

# Create your views here.

#Terima Kasih StackOverflow
def matkulView(request):
    form = matkulForm()
    form2 = matkulDelete()
    matkul = MataKuliah.objects.all()
    if request.method == 'POST':
        res = matkulForm(request.POST)
        res2 = matkulDelete(request.POST)
        if res.is_valid():
            res.save()
            tambah = True
            return render(request, 'matkul.html', {'form' : form, 'form2' : form2, 'tambah' : tambah, 'matkul': matkul})
        elif res2.is_valid():
            tujuan = MataKuliah.objects.get(pk=res2.cleaned_data['choice'].pk)
            tujuan.delete()
            hapus = True
            return render(request, 'matkul.html', {'form' : form, 'form2' : form2, 'hapus' : hapus, 'matkul': matkul})
    
    
    return render(request, 'matkul.html', {'form' : form, 'form2' : form2, 'matkul': matkul})

def matkulAllView(request, id):
    matkul = MataKuliah.objects.get(id=id)

    return render(request, 'matkul_all.html', {'matkul': matkul})

wangi/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Create your views here.
def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('loginsuccess')
        else:
            return redirect('loginerror')
    return render(request, 'wangi.html')

def loginSuccessView(request):
    context = {}
    if request.user.is_authenticated:
        context['success'] = True
    else:
        context['failed'] = True
    return render(request, 'wangi_success.html', context)

def loginErrorView(request):
    return render(request, 'wangi_error.html')

def signupView(request):
    context = {}
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        newUser = User.objects.create_user(username, email, password)
        context['success'] = True
    
    return render(request, 'wangi_signup.html', context)

def logoutView(request):
    logout(request)
    return redirect('loginbase')

accordion/templates/accordion.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery Wangi</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src='{% static "accordion.js" %}'></script>
</head>
<body>
 
<div id="accordion">
   <div>
    <div class='tombolup'>^</div>
    <div class='tomboldown'>\/</div>  
    <h3>Aktivitas Saat Ini</h3>
    <div>
        <ul>
            <li>pepew</li>
            <li>adbis bisplan</li>
            <li>adbis individu</li>
            <li>adbis refleksi</li>
            <li>ppm report</li>
            <li>ppm individu</li>
            <li>ppm refleksi</li>
            <li>AVR</li>
            <li>Esai</li>
            <li>:)</li>
        </ul>
    </div>
   </div>

   <div>
    <div class='tombolup'>^</div>
    <div class='tomboldown'>\/</div>   
    <h3>Prestasi</h3>
    <div>
        <p><b>404 NOT FOUND</b></p>
    </div>
   </div>

   <div>
    <div class='tombolup'>^</div>
    <div class='tomboldown'>\/</div> 
    <h3>Organisasi/Kepanitiaan</h3>
    <div>
        <ul>
            <li>SISTEM Consulting</li>
            <li>Pramuka UI</li>
            <li>DDP-0</li>
        </ul>
    </div>
   </div>
   
   <div>
    <div class='tombolup'>^</div>
    <div class='tomboldown'>\/</div>   
    <h3>Aktivitas Saat Ini Part 2</h3>
    <div>
        <p><b>MIHOYO STOP KASIH SAYA BUNGA REEEEEEEEEEEEEEE</b></p>
    </div>
   </div> 
  
</div>
 
 
</body>
</html>

ajax/templates/ajax.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            crossorigin="anonymous"></script>
    <title>Buku Wangi</title>
</head>
<body>
    <form id='book-form'>
        <input type="text" id="book-search">
        <input type="submit" value="Cari">
    </form>

    <div>
        <table id='book-result'>

        </table>
    </div>
    <div>
        
    </div>
    <script>
        $(document).ready(
            $('#book-form').submit(function (event) {
                event.preventDefault();

                const bookTitle = $('#book-search').val();
                $.ajax({
                    method: 'GET',
                    data: {
                      'query': bookTitle
                    },
                    url: "/ajax/response",
                    success: function (result) {
                        let bookRow = $('#book-result');
                        bookRow.empty();
                        const resultList = result['items'];
                        if (typeof resultList === 'undefined'){
                            bookRow.append(
                                "<tr>" +
                                "<td> Tidak Ditemukan </td>" +
                                "</tr>"
                            );
                        }
                        else {
                            for (let i = 0; i < resultList.length; i++) {
                                bookRow.append(
                                    "<tr>" +
                                    "<td rowspan='2'><img src=" + resultList[i]['volumeInfo']['imageLinks']['thumbnail'] + " alt='tidak ditemukan'></td>" +
                                    "<td>" + resultList[i]['volumeInfo']['title'] + "</td>" +
                                    "</tr>" + "<tr>" +
                                    "<td>" + resultList[i]['volumeInfo']['authors'][0] + "</td>" +
                                    "</tr>"
                                );
                            }
                        }
                    }
                });
            })
        );
    </script>
    
</body>
</html>

kegiatan/templates/kegiatan.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Kegiatan</title>
</head>
<body>
    <h1 style="text-align: center;">KEGIATAN</h1>
    
    <h3>Tambah Kegiatan</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form1 }}
        <input type="submit" value="Tambah Kegiatan">
    </form>
    {% if kegiatanSukses %}
        <p>Kegiatan Berhasil Ditambahkan</p>
    {% endif %}    

    <h3>List Kegiatan</h3>
    {% for instance in kegiatan %}
        <h4>{{ instance.namaKegiatan }}</h4>
        <p>Peserta:</p>
        {% for orang in instance.orang_set.all %}
        <ul>{{ orang.nama }}</ul>
        {% endfor %}
        <form action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="pkKegiatan" value="{{ instance.pk }}">
            {{ form2 }}
            <input type="submit" value="Daftar">
        </form>
        {% if daftarSukses %}
            <p>Daftar Berhasil</p>
        {% endif %}
    {% endfor %}
</body>
</html>

matkul/templates/matkul.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pencatat matkul</title>
</head>
<body>
    <h2>TAMBAH MATA KULIAH</h2>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="submit">
        </form>
    </div>
    {% if tambah %}
        <p>Matkul berhasil ditambahkan</p>
    {% endif %}

    <h2>HAPUS MATA KULIAH</h2>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form2 }}
            <input type="submit" value="submit">
        </form>
    </div>
    {% if hapus %}
        <p>Matkul berhasil dihapus</p>
    {% endif %}

    <h2>DAFTAR MATKUL</h2>
    <p>Klik nama matkul untuk mendapatkan detail</p>
    <table style="width: 20%; padding: 10px; text-align: center;">
        <tr>
            <th>No</th>
            <th>Nama Matkul</th>
        </tr>
        {% for instance in matkul %}
        <tr>
            <td>{{instance.pk}}</td>
            <td> <a href="{% url 'all' id=instance.id %}">{{instance.namaMatkul}}</a></td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

matkul/templates/matkul_all.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Matkul</title>
</head>
<body>
    <h2>DETAIL MATKUL</h2>
    <table style="width: 30%; padding: 15px; text-align: justify;">
        <tr>
            <th>No</th>
            <td>: {{ matkul.id }}</td>
        </tr>
        <tr>
            <th>Nama Matkul</th>
            <td>: {{ matkul.namaMatkul }}</td>
        </tr>
        <tr>
            <th>Dosen</th>
            <td>: {{ matkul.dosen }}</td>
        </tr>
        <tr>
            <th>SKS</th>
            <td>: {{ matkul.sks }}</td>
        </tr>
        <tr>
            <th>Deskripsi</th>
            <td>: {{ matkul.deskripsi }}</td>
        </tr>
        <tr>
            <th>Semester</th>
            <td>: {{ matkul.semester }}</td>
        </tr>
        <tr>
            <th>Ruang Kelas</th>
            <td>: {{ matkul.ruangKelas }}</td>
        </tr>
    </table>

    <p>click <a href="{% url 'catat' %}">HERE</a> to add or delete course</p>
</body>
</html>

wangi/templates/wangi.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wangi Wangi</title>
</head>
<body>
    <h1>LOGIN</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" id="username">
        <label for="password">Password</label>
        <input type="password" name="password" id="password">
        <input type="submit" value="Log In">
    </form>
    <p>Click <a href="{% url 'signup' %}">here</a> to sign up</p>
</body>
</html>

wangi/templates/wangi_error.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Error</title>
</head>
<body>
    <h1>Login gagal. Silahkan coba lagi</h1>
    <a href="{% url 'loginbase' %}">Login</a>
</body>
</html>

wangi/templates/wangi_signup.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wangi Signup</title>
</head>
<body>
    <h1>SIGN UP</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
        <label for="username">Username</label>
        <input type="text" name="username" id="username">
        <label for="password">Password</label>
        <input type="password" name="password" id="password">
        <input type="submit" value="Sign Up">
    </form>
    {% if success %}
    <p>Signup success. Click <a href="{% url 'loginbase' %}">here</a> to login</p>
    {% endif %}
</body>
</html>

wangi/templates/wangi_success.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cocogoat Wangi</title>
</head>
<body>
    {% if success %}
    <h1>Selamat, {{ request.user.username }}, anda berhasil login</h1>
    <h2>Ini ada Cocogoat</h2>
    <img src="{% static 'cocogoat.png' %}" alt="cocogoat where" style="max-width: 50vh; max-height: 25vh;">
    <a href="{% url 'logout' %}">Logout</a>
    {% endif %}

    {% if failed %}
    <h1>Silahkan login terlebih dahulu</h1>
    <a href="{% url 'loginbase' %}">Login</a>
    {% endif %}
</body>
</html>